In [150]:
import pandas as pd

In [151]:
df = pd.read_csv("final-final.csv")

/Users/Luquitas/opt/anaconda3/envs/python/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [152]:
df

,id,comuna,barrio,latitud,longitud,fecha,hora,uso_arma,uso_moto,lugar,origen_dato,tipo,subtipo,cantidad_vehiculos,cantidad_victimas
0,443198.0,Comuna 15,VILLA CRESPO,-34.599.001,-58.430.868.000.000.000,2019-05-01,20:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (con violencia),NaN,NaN,NaN
1,441418.0,Comuna 10,MONTE CASTRO,-34.618.812,-58.513.158.999.999.900,2019-05-01,21:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (con violencia),NaN,NaN,NaN
2,441342.0,Comuna 3,SAN CRISTÓBAL,-34.624.292,-58.405.671.999.999.900,2019-05-01,19:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (con violencia),NaN,NaN,NaN
3,441537.0,Comuna 15,CHACARITA,-34.590.214,-58.449.175,2019-05-01,6:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (con violencia),NaN,NaN,NaN
4,441421.0,Comuna 4,NUEVA POMPEYA,-34.652.885.999.999.900,-5.843.164.399.999.990,2019-05-01,10:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (con violencia),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123740,396112.0,Comuna 7,FLORES,NaN,NaN,2019-06-30,17:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,NaN,NaN
123741,396115.0,Comuna 11,VILLA GRAL. MITRE,NaN,NaN,2019-06-30,20:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,NaN,NaN
123742,396128.0,Comuna 13,BELGRANO,NaN,NaN,2019-06-30,19:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,NaN,NaN
123743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIN MOTO,NaN,NaN,NaN,NaN,NaN,NaN
123744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIN MOTO,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df["tipo"].unique()

array(['Robo (con violencia)', 'Robo Automotor', 'Hurto (sin violencia)',
       'Hurto Automotor', 'Homicidio Doloso', 'Homicidio', 'Lesiones',
       nan], dtype=object)

In [155]:
df.replace(to_replace="Lesiones", value = "Lesiones Seg Vial", inplace= True)

In [156]:
df.replace(to_replace="Homicidio", value = "Homicidio Seg Vial", inplace= True)

In [157]:
df.replace(to_replace="Robo (con violencia)", value = "Robo (Con violencia)", inplace= True)

In [158]:
df.replace(to_replace="Hurto (sin violencia)", value = "Hurto (Sin violencia)", inplace= True)

In [159]:
df.tipo.value_counts()

Robo (Con violencia)     61368
Hurto (Sin violencia)    44617
Hurto Automotor           9308
Lesiones Seg Vial         5408
Robo Automotor            2856
Homicidio Doloso            94
Homicidio Seg Vial          92
Name: tipo, dtype: int64

In [160]:
df["cantidad_vehiculos"].replace(to_replace="Comuna 2", value = 2, inplace=True)

In [161]:
df["cantidad_vehiculos"].replace(to_replace="Comuna 1", value = 1, inplace=True)

In [162]:
df["cantidad_vehiculos"].fillna(0, inplace=True)

In [163]:
df["cantidad_victimas"].fillna(0, inplace=True)

In [164]:
df

,id,comuna,barrio,latitud,longitud,fecha,hora,uso_arma,uso_moto,lugar,origen_dato,tipo,subtipo,cantidad_vehiculos,cantidad_victimas
0,443198.0,Comuna 15,VILLA CRESPO,-34.599.001,-58.430.868.000.000.000,2019-05-01,20:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (Con violencia),NaN,0.0,0.0
1,441418.0,Comuna 10,MONTE CASTRO,-34.618.812,-58.513.158.999.999.900,2019-05-01,21:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (Con violencia),NaN,0.0,0.0
2,441342.0,Comuna 3,SAN CRISTÓBAL,-34.624.292,-58.405.671.999.999.900,2019-05-01,19:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (Con violencia),NaN,0.0,0.0
3,441537.0,Comuna 15,CHACARITA,-34.590.214,-58.449.175,2019-05-01,6:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (Con violencia),NaN,0.0,0.0
4,441421.0,Comuna 4,NUEVA POMPEYA,-34.652.885.999.999.900,-5.843.164.399.999.990,2019-05-01,10:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Robo (Con violencia),NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123740,396112.0,Comuna 7,FLORES,NaN,NaN,2019-06-30,17:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,0.0,0.0
123741,396115.0,Comuna 11,VILLA GRAL. MITRE,NaN,NaN,2019-06-30,20:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,0.0,0.0
123742,396128.0,Comuna 13,BELGRANO,NaN,NaN,2019-06-30,19:00:00,SIN USO DE ARMA,SIN MOTO,NaN,NaN,Hurto Automotor,Hurto Automotor,0.0,0.0
123743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIN MOTO,NaN,NaN,NaN,NaN,0.0,0.0
123744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIN MOTO,NaN,NaN,NaN,NaN,0.0,0.0

In [165]:
df["id"].dropna(inplace=True)
df["id"].isna().sum()

0

In [166]:
df["id"] = df.id.astype(int)
df['cantidad_vehiculos'] = df.cantidad_vehiculos.astype(int)
df['cantidad_victimas'] = df.cantidad_victimas.astype(int)

In [167]:
df.drop(columns="subtipo", inplace=True)

In [168]:
df.rename(columns={"tipo":"tipo_delito"}, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123745 entries, 0 to 123744
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  123743 non-null  float64
 1   comuna              123136 non-null  object
 2   barrio              123136 non-null  object
 3   latitud             38024 non-null   object
 4   longitud            38024 non-null   object
 5   fecha               123743 non-null  object
 6   hora                123743 non-null  object
 7   uso_arma            123743 non-null  object
 8   uso_moto            123745 non-null  object
 9   lugar               0 non-null       float64
 10  origen_dato         0 non-null       float64
 11  tipo_delito         123743 non-null  object
 12  cantidad_vehiculos  123745 non-null  int64
 13  cantidad_victimas   123745 non-null  int64
dtypes: float64(3), int64(2), object(9)
memory usage: 13.2+ MB

In [170]:
df.to_csv('deilitos2019.csv', header=False, index=False)

In [171]:
df_a_copiar = pd.read_csv("delitos.csv")

In [174]:
df_a_descargar = df_a_copiar.append(df)

In [178]:
df_a_descargar.to_csv("delitos_caba20162019.csv", index=False)